In [1]:
from typing import TypeVar


T = TypeVar('T')

def pr(val : T , title:str|None = None , description: str|None = None) : # type: ignore
    if title != None :
        print(f" ---------------------- {title} ---------------------- ")
        if description != None :
            print(f" <-- {description} -->")
    print('type: ' , type(val))
    display(val)
    # return val

In [ ]:
%matplotlib inline
from __future__ import annotations

from typing import TypeVar, Iterable, Optional, Sequence, Tuple  , Final# type: ignore
import numpy as np # type: ignore
import numpy.typing as npt # type: ignore
import pandas as pd # type: ignore

# Matplotlib imports with types
import matplotlib.pyplot as plt # type: ignore
from matplotlib.figure import Figure # type: ignore
from matplotlib.axes import Axes # type: ignore

In [11]:
# ---- 1) Reproducible random seed --------------------------------------------
from datetime import timedelta


SEED: Final[int] = 42
rng = np.random.default_rng(SEED)
# ---- 2) Generate synthetic orders -------------------------------------------
N_ORDERS: Final[int] = 60
DAYS:Final[int] = 14
CUSTOMERS: Final[Tuple[str , ...]] = ("Alice", "Bob", "Carol", "Dave", "Eve", "Frank")
CATEGORIES: Final[Tuple[str , ...]] = ("Grocery", "Electronics", "Books")
start = pd.Timestamp('today').normalize() 
end = pd.Timestamp('today').normalize() + timedelta(days=DAYS)
date_index = pd.date_range(start , end , freq="D")
pr(start , 'start')
pr(end , 'end')
pr(date_index , 'date_index')


 ---------------------- start ---------------------- 
type:  <class 'pandas._libs.tslibs.timestamps.Timestamp'>


Timestamp('2025-10-22 00:00:00')

 ---------------------- end ---------------------- 
type:  <class 'pandas._libs.tslibs.timestamps.Timestamp'>


Timestamp('2025-11-05 00:00:00')

 ---------------------- date_index ---------------------- 
type:  <class 'pandas.core.indexes.datetimes.DatetimeIndex'>


DatetimeIndex(['2025-10-22', '2025-10-23', '2025-10-24', '2025-10-25',
               '2025-10-26', '2025-10-27', '2025-10-28', '2025-10-29',
               '2025-10-30', '2025-10-31', '2025-11-01', '2025-11-02',
               '2025-11-03', '2025-11-04', '2025-11-05'],
              dtype='datetime64[ns]', freq='D')

In [16]:
# Sample columns
order_dates :npt.NDArray[np.datetime64] = rng.choice(date_index.values ,size=N_ORDERS , replace=True)
order_ids  = np.arange(1  , N_ORDERS + 1 , dtype=np.int64 )
pr(order_dates[:10] , 'order_dates')
pr(order_ids[:10] , 'order_ids')

 ---------------------- order_dates ---------------------- 
type:  <class 'numpy.ndarray'>


array(['2025-11-05T00:00:00.000000000', '2025-10-24T00:00:00.000000000',
       '2025-10-29T00:00:00.000000000', '2025-11-01T00:00:00.000000000',
       '2025-10-29T00:00:00.000000000', '2025-10-28T00:00:00.000000000',
       '2025-10-24T00:00:00.000000000', '2025-10-27T00:00:00.000000000',
       '2025-10-25T00:00:00.000000000', '2025-10-26T00:00:00.000000000'],
      dtype='datetime64[ns]')

 ---------------------- order_ids ---------------------- 
type:  <class 'numpy.ndarray'>


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
customer_props : npt.NDArray[np.float64] = np.array([0.22, 0.18, 0.16, 0.16, 0.14, 0.14] , dtype=np.float64)
customers  = rng.choice(CUSTOMERS , size=N_ORDERS ,p=customer_props , replace=True)
categories = rng.choice(CATEGORIES , size=N_ORDERS , replace=True)
pr(customer_props , 'customer_props')
pr(customers , 'customers')
pr(categories , 'categories')

 ---------------------- customer_props ---------------------- 
type:  <class 'numpy.ndarray'>


array([0.22, 0.18, 0.16, 0.16, 0.14, 0.14])

 ---------------------- customers ---------------------- 
type:  <class 'numpy.ndarray'>


array(['Alice', 'Alice', 'Alice', 'Dave', 'Carol', 'Eve', 'Dave', 'Bob',
       'Frank', 'Eve', 'Bob', 'Bob', 'Bob', 'Alice', 'Alice', 'Frank',
       'Carol', 'Bob', 'Eve', 'Carol', 'Frank', 'Eve', 'Carol', 'Bob',
       'Frank', 'Dave', 'Frank', 'Alice', 'Eve', 'Dave', 'Alice', 'Dave',
       'Dave', 'Alice', 'Carol', 'Eve', 'Bob', 'Carol', 'Carol', 'Bob',
       'Frank', 'Eve', 'Alice', 'Frank', 'Frank', 'Bob', 'Eve', 'Alice',
       'Frank', 'Dave', 'Dave', 'Alice', 'Frank', 'Alice', 'Bob', 'Alice',
       'Eve', 'Alice', 'Frank', 'Dave'], dtype='<U5')

 ---------------------- categories ---------------------- 
type:  <class 'numpy.ndarray'>


array(['Books', 'Books', 'Grocery', 'Grocery', 'Grocery', 'Grocery',
       'Grocery', 'Books', 'Electronics', 'Books', 'Books', 'Books',
       'Grocery', 'Grocery', 'Books', 'Grocery', 'Grocery', 'Books',
       'Books', 'Books', 'Books', 'Grocery', 'Books', 'Books', 'Books',
       'Books', 'Books', 'Electronics', 'Grocery', 'Electronics',
       'Grocery', 'Grocery', 'Grocery', 'Books', 'Electronics',
       'Electronics', 'Books', 'Electronics', 'Electronics', 'Grocery',
       'Books', 'Electronics', 'Grocery', 'Books', 'Books', 'Grocery',
       'Grocery', 'Grocery', 'Grocery', 'Grocery', 'Books', 'Electronics',
       'Books', 'Books', 'Electronics', 'Electronics', 'Grocery',
       'Grocery', 'Electronics', 'Grocery'], dtype='<U11')

In [28]:
quantities : npt.NDArray[np.int64] = rng.integers(1,6, size=N_ORDERS  , endpoint=False , dtype=np.int64)
unit_prices: npt.NDArray[np.int64] = rng.integers(5,121 , size=N_ORDERS , endpoint=False , dtype=np.int64) 
pr(quantities , 'quantities')
pr(unit_prices , 'unit_prices')

 ---------------------- quantities ---------------------- 
type:  <class 'numpy.ndarray'>


array([1, 5, 5, 5, 1, 1, 2, 3, 2, 3, 1, 4, 2, 1, 4, 5, 1, 3, 5, 4, 5, 3,
       2, 4, 1, 2, 4, 4, 1, 3, 2, 3, 5, 1, 5, 3, 4, 3, 2, 4, 4, 1, 4, 4,
       2, 5, 4, 2, 1, 4, 2, 4, 3, 3, 1, 4, 1, 3, 5, 5])

 ---------------------- unit_prices ---------------------- 
type:  <class 'numpy.ndarray'>


array([119, 116,  69,  28, 102,  97, 119,  80,  21,  63,  56, 102,  50,
        43,  14, 101,  92,   9,  55,  60,  59, 111,  22,  40,  25,  33,
       110, 114,  10,  78,  32,  27,  38,  27,  61, 120,  73,  88,  62,
         6,  14,  36,  33, 102, 102, 104,  78,  69,  80,  52,  82,  97,
        93,  76,  11,  89,  47,  91,  67, 107])

In [42]:
orders:pd.DataFrame = pd.DataFrame({
    "order_id" : order_ids ,
    "date" : pd.to_datetime(order_dates),
    "customer" : customers , 
    "category":categories,
    "qty" : quantities ,
    "unit_price": unit_prices
}).sort_values(['date' , 'order_id'], ignore_index=True)
pr(orders.head(20))
pr(orders.dtypes)

type:  <class 'pandas.core.frame.DataFrame'>


order_id       date customer     category  qty  unit_price
0         53 2025-10-22    Frank        Books    3          93
1         16 2025-10-23    Frank      Grocery    5         101
2         18 2025-10-23      Bob        Books    3           9
3         37 2025-10-23      Bob        Books    4          73
4         38 2025-10-23    Carol  Electronics    3          88
5         41 2025-10-23    Frank        Books    4          14
6          2 2025-10-24    Alice        Books    5         116
7          7 2025-10-24     Dave      Grocery    2         119
8         50 2025-10-24     Dave      Grocery    4          52
9          9 2025-10-25    Frank  Electronics    2          21
10        26 2025-10-25     Dave        Books    2          33
11        29 2025-10-25      Eve      Grocery    1          10
12        31 2025-10-25    Alice      Grocery    2          32
13        44 2025-10-25    Frank        Books    4         102
14        10 2025-10-26      Eve        Books    3          63
15        36 2025-10-26      Eve  Electronics    3         120
16        46 2025-10-26      Bob      Grocery    5         104
17        59 2025-10-26    Frank  Electronics    5          67
18         8 2025-10-27      Bob        Books    3          80
19        14 2025-10-27    Alice      Grocery    1          43

type:  <class 'pandas.core.series.Series'>


order_id               int64
date          datetime64[ns]
customer              object
category              object
qty                    int64
unit_price             int64
dtype: object